// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData } from "./tables/Position.sol";
import { WorldEffect, WorldEffectData } from "./tables/WorldEffect.sol";
import { SpawnRecord, SpawnRecordData } from "./tables/SpawnRecord.sol";
import { WorldCaption, WorldCaptionData } from "./tables/WorldCaption.sol";
import { WorldPatchLog, WorldPatchLogData } from "./tables/WorldPatchLog.sol";
import { PatchCounter } from "./tables/PatchCounter.sol";
