// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IWorldPatchSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWorldPatchSystem {
  function app__setEffect(bytes32 zoneId, bytes32 effect, bytes3 color, uint8 intensity) external;

  function app__spawnEntity(bytes32 entityType, int32 x, int32 y) external returns (bytes32);

  function app__setCaption(bytes32 zoneId, string calldata caption) external;

  function app__applyWorldPatch(
    bytes32 effect,
    bytes3 color,
    uint8 intensity,
    bytes32 spawnType,
    int32 spawnX,
    int32 spawnY,
    string calldata caption
  ) external;
}
